language: ruby
rvm:
  - 1.8.7 # (current default)
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-18mode
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
